export const CALCI_ACTIONS = {
  SET_A: 'SET_A',
  SET_B: 'SET_B',
  GET_ADDITION: 'GET_ADDITION',
  GET_SUBTRACTION: 'GET_SUBTRACTION',
  GET_MULTIPLICATION: 'GET_MULTIPLICATION',
  GET_DIVISION: 'GET_DIVISION',
  RESET_STATE: 'RESET_STATE',
};
